services:
  - type: web
    name: kokzhiek-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: node
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true